name: Continuous Integration Workflow
on: [push, pull_request]

jobs:
  build:
    name: Build and Test
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@master

      - run: dotnet restore
      - run: dotnet build --no-restore --configuration Release
      - run: dotnet test --no-build --configuration Release
      - run: dotnet publish --no-build --configuration Release --output staging/Blazor ./src/NPacMan.Blazor/
      
      - name: Upload blazor site
        uses: actions/upload-artifact@v1
        with:
          name: blazor
          path: staging/Blazor

  deploy_blazor:
    name: Deploy Blazor
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'refs/heads/gh-pages'
        path: 'blazor/wwwroot'
    - name: Download blazor site
      uses: actions/download-artifact@v1
      with:
        name: blazor
        path: ./blazor
    - run: |
       cd blazor
       cd wwwroot
       sed -i 's/<base href="\/" \/>/<base href="\/PacMan\/" \/>/g' index.html
       
       git config user.name "ci@yorkdevelopers.org"
       git config user.email "ci@yorkdevelopers.org"
       git add .
       git commit -m "Updating site"
       git push
       
