name: Continuous Integration Workflow
on: [push, pull_request]

jobs:
  build:
    name: Build and Test
    runs-on: windows-latest
    steps:
      - run: echo {{ github.ref }}
      - run: echo {{ github.event_name }}
      - uses: actions/checkout@master

      - run: dotnet restore
      - run: dotnet build --no-restore --configuration Release
      - run: dotnet test --no-build --configuration Release
      - run: dotnet publish --no-build --configuration Release --output staging/Blazor ./src/NPacMan.Blazor/
      - name: Deploy 🚀
        if: ${{ github.event_name == 'push' && github.ref == 'ref/heads/master' }}
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: staging/Blazor/wwwroot # The folder the action should deploy.